use crate::arch::{KERNEL_VIRTUAL_BASE, PAGE_TABLE_LEVEL2_SHIFT, VIRTUAL_PAGE_NUMBER_MASK};

pub const KERNEL_LEVEL2_INDEX: usize =
    (KERNEL_VIRTUAL_BASE >> PAGE_TABLE_LEVEL2_SHIFT) & VIRTUAL_PAGE_NUMBER_MASK;
