[package]
name = "ferrum-core"
version = "0.1.0"
edition = "2021"

[dependencies]
spinlock = { git = "https://github.com/AlexVplle/spinlock" }
lock_dependency = { path = "../../lockdep" }

[target.'cfg(target_arch = "riscv64")'.dependencies]
sbi = { path = "../../sbi" }

[features]
fuzz = []

[target.'cfg(loom)'.dependencies]
loom = "0.7"

[dev-dependencies]
proptest = "1"
