use crate::arch::{PAGE_TABLE_LEVEL1_SHIFT, VIRTUAL_PAGE_NUMBER_MASK};

pub const FIXMAP_BASE: usize = 0xFFC00000;
pub const FIXMAP_LEVEL1_INDEX: usize =
    (FIXMAP_BASE >> PAGE_TABLE_LEVEL1_SHIFT) & VIRTUAL_PAGE_NUMBER_MASK;
