use crate::arch::{
    GIGA_PAGE_MASK, GIGA_PAGE_SIZE, KERNEL_VIRTUAL_BASE, PAGE_TABLE_LEVEL1_SHIFT,
    PAGE_TABLE_LEVEL2_SHIFT, VIRTUAL_PAGE_NUMBER_MASK,
};

pub const FIXMAP_BASE: usize = (KERNEL_VIRTUAL_BASE & GIGA_PAGE_MASK) - GIGA_PAGE_SIZE;
pub const FIXMAP_LEVEL2_INDEX: usize = (FIXMAP_BASE >> PAGE_TABLE_LEVEL2_SHIFT) & VIRTUAL_PAGE_NUMBER_MASK;
pub(super) const FIXMAP_LEVEL1_INDEX: usize = (FIXMAP_BASE >> PAGE_TABLE_LEVEL1_SHIFT) & VIRTUAL_PAGE_NUMBER_MASK;
