use crate::arch::{KERNEL_VIRTUAL_BASE, PAGE_TABLE_LEVEL1_SHIFT, VIRTUAL_PAGE_NUMBER_MASK};

pub const KERNEL_LEVEL1_INDEX: usize =
    (KERNEL_VIRTUAL_BASE >> PAGE_TABLE_LEVEL1_SHIFT) & VIRTUAL_PAGE_NUMBER_MASK;
