[package]
name = "ferrum"
version = "0.1.0"
edition = "2024"

[dependencies]
sbi = { path = "../../sbi" }
ferrum-core = { path = "../ferrum-core" }
lock_dependency = { path = "../../lockdep" }
ferrum-macros = { path = "../ferrum-macros" }
ferrum-mm = { path = "../ferrum-mm", features = ["debug"] }
ferrum-process = { path = "../ferrum-process" }
fdt = "0.1.5"

[[bin]]
name = "ferrum"
test = false
bench = false
